name: Build and save my Docker image to a regitry

on:
  push:
    branches:
      - main  # Déclenchement lorsque le code est poussé sur main

env:
  REG_NAME: "exo.container-registry.com/c213-emf" # Nom du registre sans "azurecr.io"
  IMAGE_NAME: "todo-app:dd" # Nom de votre image dans acr

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t todo-app:dd -f ./src/backend/Dockerfile ./src/backend/
        
      - name: Push Docker image to registry
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} ${{ env.REG_NAME }}
          docker push ${{ env.REG_NAME }}/${{ env.IMAGE_NAME }}
          
