# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - WebAppDaSilva

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://acr300622210.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_915ed7539bb941bc8f1c76ef401f959f }}
        password: ${{ secrets.AzureAppService_ContainerPassword_73cc2ab74b2e4ba588b8429080a53e1f }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: acr300622210.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_915ed7539bb941bc8f1c76ef401f959f }}/todo-app:${{ github.sha }}
        file: ./src/backend/dockerfile
        context: ./src/backend

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'WebAppDaSilva'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_d78f095af2fd424f88f1518f07c9c03d }}
        images: 'acr300622210.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_915ed7539bb941bc8f1c76ef401f959f }}/todo-app:${{ github.sha }}'
